### ISSUE TITLE
Emacs 28.2 byte compiler warnings

### ISSUE THREAD

**Issue by pierre-rouleau** [HaraldJoerg/cperl-mode#16]
The following byte compiler warnings are shown on cperl-mode.el code as of today on latest commit of Nov 17, 2021:

1. Warning (bytecomp): custom-declare-variable `cperl-indent-subs-specially' docstring wider than 80 characters
2. Warning (bytecomp): assignment to free variable ‘cperl-tags-hier-regexp-list’
3. Warning (bytecomp): defsubst ‘cperl-after-sub-regexp’ was used before it was defined
4. Warning (bytecomp):  docstring wider than 80 characters [3 times]
5. Warning (bytecomp): Variable ‘l3’ left uninitialized
6. Warning (bytecomp): Variable ‘l2’ left uninitialized
7. Warning (bytecomp): Variable ‘l1’ left uninitialized [2 times]
8. Warning (bytecomp): assignment to free variable ‘facemenu-end-add-face’
9. Warning (bytecomp): the function ‘edebug-backtrace’ is not known to be defined.

**Comment by HaraldJoerg** [comment]
Thanks for the reminder!  These warnings are now gone.
I admit that my current focus is on the upstream branch (which still doesn't contain the experimental Moose etc support), but of course maintenance of the master branch will continue.
